// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'features/recents/data/models/recent_calls.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 661755399947752582),
    name: 'RecentCallEntity',
    lastPropertyId: const obx_int.IdUid(7, 6959831930144138143),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4431515951635253667),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2380150288008148213),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 164684058115681441),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3629082753303698180),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4496403528350518076),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6057968148340250874),
        name: 'callTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6959831930144138143),
        name: 'simNumber',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6009832948164404529),
    lastIndexId: const obx_int.IdUid(2, 7020718015760467611),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      5490134095863070759,
      3130716851358388790,
      8296614410940130872,
      6009832948164404529,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3159367242214690566,
      3025916304853472201,
      1839559343724453746,
      5736702297189296602,
      8657377132596357409,
      9043123941580051961,
      2485496861647735794,
      2654578565469083360,
      8793770246221430665,
      8371416544103031036,
      3081770792408261831,
      5318460539018842769,
      1977635480159000644,
      3987254982685156246,
      6092904647696910603,
      3883139867110059478,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RecentCallEntity: obx_int.EntityDefinition<RecentCallEntity>(
      model: _entities[0],
      toOneRelations: (RecentCallEntity object) => [],
      toManyRelations: (RecentCallEntity object) => {},
      getId: (RecentCallEntity object) => object.id,
      setId: (RecentCallEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RecentCallEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final simNumberOffset = object.simNumber == null
            ? null
            : fbb.writeString(object.simNumber!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, phoneNumberOffset);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(4, object.durationSeconds);
        fbb.addInt64(5, object.callTypeIndex);
        fbb.addOffset(6, simNumberOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final callTypeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final simNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = RecentCallEntity(
          name: nameParam,
          phoneNumber: phoneNumberParam,
          timestamp: timestampParam,
          durationSeconds: durationSecondsParam,
          callTypeIndex: callTypeIndexParam,
          simNumber: simNumberParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RecentCallEntity] entity fields to define ObjectBox queries.
class RecentCallEntity_ {
  /// See [RecentCallEntity.id].
  static final id = obx.QueryIntegerProperty<RecentCallEntity>(
    _entities[0].properties[0],
  );

  /// See [RecentCallEntity.name].
  static final name = obx.QueryStringProperty<RecentCallEntity>(
    _entities[0].properties[1],
  );

  /// See [RecentCallEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<RecentCallEntity>(
    _entities[0].properties[2],
  );

  /// See [RecentCallEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<RecentCallEntity>(
    _entities[0].properties[3],
  );

  /// See [RecentCallEntity.durationSeconds].
  static final durationSeconds = obx.QueryIntegerProperty<RecentCallEntity>(
    _entities[0].properties[4],
  );

  /// See [RecentCallEntity.callTypeIndex].
  static final callTypeIndex = obx.QueryIntegerProperty<RecentCallEntity>(
    _entities[0].properties[5],
  );

  /// See [RecentCallEntity.simNumber].
  static final simNumber = obx.QueryStringProperty<RecentCallEntity>(
    _entities[0].properties[6],
  );
}
